# Generated by Django 2.2.13 on 2020-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200627_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=[('GCSE', 'GSCE'), ('A-Level', 'A-Level'), ('AS-Level', 'AS'), ('BTEC', 'BTEC'), ('Degree', 'Degree')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
